[project]
name = "anikoto" 
version = "0.1.1"
description = "Download Anime from https://anikoto.tv/"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [{name = "testingbetaversion", email = ""}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
      'requests',
        'yt-dlp',
        'bs4',
]

[project.scripts]
anikoto = "anikoto.anikoto:main"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
