name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile anikoto/anikoto.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: anikoto
        path: dist/anikoto.exe
